In [9]:
import numpy as np

# np.mean -> calculate the mean of an array
arr = np.array([1,2,3,4,5])
np.mean(arr)

3.0

In [11]:
arr = np.arange(1,11)
np.mean(arr)

5.5

In [13]:
# np.std() -> compute the standard deviation of an array
np.std(arr)

2.8722813232690143

In [15]:
# np.var() -> compute the variance of an array
np.var(arr)

8.25

In [17]:
np.min(arr)

1

In [19]:
np.max(arr)

10

In [21]:
np.sum(arr)

55

In [23]:
np.prod(arr)

3628800

In [25]:
np.median(arr)

5.5

In [29]:
np.percentile(arr,60)

6.3999999999999995

In [31]:
np.argmin(arr)

0

In [33]:
np.argmax(arr)

9

In [35]:
np.unique(arr)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.diff(arr)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [39]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [41]:
np.linspace(0,10,5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [63]:
arr1 = np.arange(1,11)


In [65]:
np.corrcoef(arr,arr1)


array([[1., 1.],
       [1., 1.]])