In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr.dtype

dtype('int32')

In [3]:
arr = np.array([1.2,3.4,5.6])
arr.dtype


dtype('float64')

In [7]:
arr1 = arr.astype(np.int32)

In [9]:
arr1

array([1, 3, 5])

In [11]:
arr1.dtype

dtype('int32')

In [13]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)

In [15]:
arr_large.dtype

dtype('int64')

In [17]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [19]:
arr = np.array(['apple','banana','cherry'],dtype = 'U10')
arr

array(['apple', 'banana', 'cherry'], dtype='<U10')

In [21]:
arr = np.array([1+2j,3+4j,5+6j],dtype = 'complex128')
arr

array([1.+2.j, 3.+4.j, 5.+6.j])

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = []

# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)

print(result)  # Output: [1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]


In [25]:
arr = np.array([12,23,34,45,65])
arr = arr+10
arr

array([22, 33, 44, 55, 75])

In [27]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]

[[2 4 6]
 [5 7 9]]


In [31]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
