In [31]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

array([1, 2, 3])

In [9]:
np.sum(arr,axis =0)

array([12, 15, 18])

In [11]:
np.sum(arr,axis =1)

array([ 6, 15, 24])

In [13]:
arr[0][1]

2

In [15]:
arr[0,1]

2

In [19]:
arr[0:2,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [23]:
arr3D.shape

(2, 2, 3)

In [25]:
arr3D[0,1,2]

6

In [29]:
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [33]:
a = arr[:,0]

In [35]:
a

array([1, 4, 7])

In [37]:
b = arr3D[:,0,:]

In [39]:
b

array([[1, 2, 3],
       [7, 8, 9]])

In [41]:
arr[:,1] = 0

In [43]:
arr

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])